apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: mce
data:
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT_ID: "343938549827"
  # Replace these placeholders with Terraform outputs or CI patching:
  RDS_HOST: "<RDS_HOST_PLACEHOLDER>"
  RDS_PORT: "5432"
  KAFKA_BOOTSTRAP: "<KAFKA_BOOTSTRAP_PLACEHOLDER>"     # e.g. b-1.mcekafka.xxxx:9092,b-2...
  OPENSEARCH_ENDPOINT: "<OPENSEARCH_ENDPOINT_PLACEHOLDER>"  # e.g. https://search-mce-...
  DYNAMODB_TABLE_CART: "mce-cart-mce"
  PRODUCT_SERVICE_URL: "http://product.mce.svc.cluster.local"
  ORDER_SERVICE_URL: "http://order.mce.svc.cluster.local"
  CART_SERVICE_URL: "http://cart.mce.svc.cluster.local"
  SEARCH_SERVICE_URL: "http://search.mce.svc.cluster.local"
